# Copyright (C) 2019  SuperGreenLab <towelie@supergreenlab.com>
# Author: Constantin Clauzel <constantin.clauzel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: SuperGreenOSTemplate
modules:

  #
  # Core modules
  #
  - core/wifi/wifi.h
  - core/ble/ble.h
  - core/kv/kv.h
  - core/ota/ota.h
  - core/httpd/httpd.h
  - core/stat_dump/stat_dump.h
  - core/time/time.h
  - core/mqtt/mqtt.h

keys:

  #
  # Core keys
  #
  - name: WIFI_STATUS
    type: i
    ble:
      uuid: {0xee,0x06,0x0e,0xb5,0x31,0xae,0x83,0xf0,0xda,0xcb,0x67,0x6d,0x1c,0xda,0x2f,0x37}
      notify: true
    default: 0

  - name: WIFI_SSID
    type: str
    nvs:
      key: WSSID
    ble:
      uuid: {0x17,0xfe,0xc3,0xc1,0x6b,0xe1,0x15,0x54,0xa5,0x74,0x55,0x9c,0x81,0x69,0xa3,0x6c}
      write: true
    write_cb: on_set_wifi_ssid
    default: ""

  - name: WIFI_PASS
    type: str
    nvs:
      key: WPASS
    ble:
      uuid: {0xb9,0x5d,0x53,0x82,0x6e,0xcc,0xa0,0xfe,0xf1,0xa6,0xfe,0x6c,0x10,0x0b,0xe4,0xf7}
      write: true
      notify: true
    write_cb: on_set_wifi_password
    default: ""

  - name: TIME
    type: i
    nvs:
      key: TIME
    ble:
      uuid: {0x9b,0x6a,0x3b,0xe2,0xaa,0xb4,0x33,0xaa,0x8a,0x4a,0x9e,0xe1,0x4f,0xee,0xf9,0x40}
      write: true
      notify: true
    write_cb: on_set_time
    default: 0
 
  - name: OTA_TIMESTAMP
    type: i
    nvs:
      key: OTA_TS
    ble:
      uuid: {0x89,0x6e,0x49,0xd6,0x82,0x21,0x7e,0xce,0x96,0x23,0xc9,0xe3,0x2b,0x16,0x6f,0x61}
      write: true
    write_cb: on_set_ota_timestamp
    default: CONFIG_OTA_TIMESTAMP

  - name: OTA_SERVER_IP
    type: s
    nvs:
      key: OTA_SRV_IP
    ble:
      uuid: {0xda,0x84,0xdb,0xbc,0x5f,0x7d,0x86,0xf5,0x10,0xf0,0xae,0xaa,0x05,0xdb,0xb8,0xf7}
      write: true
    write_cb: on_set_ota_server_ip
    default: CONFIG_OTA_SERVER_IP

  - name: OTA_SERVER_HOSTNAME
    type: s
    nvs:
      key: OTA_SRV_HN
    ble:
      uuid: {0x3c,0x3d,0xce,0xb9,0x11,0x81,0xce,0x11,0xe6,0x13,0xab,0x05,0x47,0x6a,0xa2,0xfa}
      write: true
    write_cb: on_set_ota_server_hostname
    default: CONFIG_OTA_SERVER_HOSTNAME
