# Copyright (C) 2019  SuperGreenLab <towelie@supergreenlab.com>
# Author: Constantin Clauzel <constantin.clauzel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

modules:

  #
  # Core modules
  #
  - core/wifi/wifi.h
  - core/ble/ble.h
  - core/kv/kv.h
  - core/ota/ota.h
  - core/httpd/httpd.h
  - core/stat_dump/stat_dump.h
  - core/time/time.h
  - core/mqtt/mqtt.h
  - core/i2c/i2c.h

  #
  # Custom modules
  #
  - blower/blower.h
  - fans/fans.h
  - led/led.h
  - mixer/mixer.h
  - state/state.h
  - status_led/status_led.h
  - timers/timer.h
  - timers/onoff/onoff.h

keys:

  #
  # Core keys
  #
  - name: wifi_status
    caps_name: WIFI_STATUS
    integer: true
    ble:
      uuid: "{0xee,0x06,0x0e,0xb5,0x31,0xae,0x83,0xf0,0xda,0xcb,0x67,0x6d,0x1c,0xda,0x2f,0x37}"
      notify: true
    default_var: DISCONNECTED

  - name: wifi_ssid
    caps_name: WIFI_SSID
    string: true
    nvs:
      key: WSSID
    ble:
      first: true
      uuid: "{0x17,0xfe,0xc3,0xc1,0x6b,0xe1,0x15,0x54,0xa5,0x74,0x55,0x9c,0x81,0x69,0xa3,0x6c}"
      write: true
    http:
      write: true
    write_cb: true
    default: 

  - name: wifi_password
    caps_name: WIFI_PASS
    string: true
    nvs:
      key: WPASS
      manual: true
    ble:
      uuid: "{0xb9,0x5d,0x53,0x82,0x6e,0xcc,0xa0,0xfe,0xf1,0xa6,0xfe,0x6c,0x10,0x0b,0xe4,0xf7}"
      write: true
      notify: true
      no_sync: true
    http:
      write: true
    write_cb: true
    default: ""

  - name: time
    caps_name: TIME
    integer: true
    nvs:
      key: TIME
    ble:
      uuid: "{0x9b,0x6a,0x3b,0xe2,0xaa,0xb4,0x33,0xaa,0x8a,0x4a,0x9e,0xe1,0x4f,0xee,0xf9,0x40}"
      write: true
      notify: true
    http:
      write: true
    write_cb: true
    default: 0
 
  - name: ota_timestamp
    caps_name: OTA_TIMESTAMP
    integer: true
    ble:
      uuid: "{0x89,0x6e,0x49,0xd6,0x82,0x21,0x7e,0xce,0x96,0x23,0xc9,0xe3,0x2b,0x16,0x6f,0x61}"
    http:
      noop: true
    default_var: OTA_TIMESTAMP

  - name: ota_server_ip
    caps_name: OTA_SERVER_IP
    string: true
    nvs:
      key: OTA_SRV_IP
    ble:
      uuid: "{0xda,0x84,0xdb,0xbc,0x5f,0x7d,0x86,0xf5,0x10,0xf0,0xae,0xaa,0x05,0xdb,0xb8,0xf7}"
      write: true
    http:
      write: true
    default_var: CONFIG_OTA_SERVER_IP

  - name: ota_server_hostname
    caps_name: OTA_SERVER_HOSTNAME
    string: true
    nvs:
      key: OTA_SRV_HN
    ble:
      uuid: "{0x3c,0x3d,0xce,0xb9,0x11,0x81,0xce,0x11,0xe6,0x13,0xab,0x05,0x47,0x6a,0xa2,0xfa}"
      write: true
    http:
      write: true
    default_var: CONFIG_OTA_SERVER_HOSTNAME

  - name: ota_server_port
    caps_name: OTA_SERVER_PORT
    string: true
    nvs:
      key: OTA_SRV_PRT
    ble:
      uuid: "{0x6a,0xe5,0xac,0x03,0xe2,0xe0,0x6f,0x79,0x75,0x69,0xe0,0xeb,0x38,0xbd,0x35,0x6c}"
      write: true
    http:
      write: true
    default_var: CONFIG_OTA_SERVER_PORT

  - name: ota_version_filename
    caps_name: OTA_VERSION_FILENAME
    string: true
    nvs:
      key: OTA_VR_FILE
    ble:
      uuid: "{0x52,0x7b,0x93,0xa6,0x52,0x22,0x4c,0xb2,0x3f,0xc9,0x16,0x3e,0x7d,0xf5,0xe5,0x1e}"
      write: true
    http:
      write: true
    default_var: CONFIG_OTA_VERSION_FILENAME

  - name: ota_filename
    caps_name: OTA_FILENAME
    string: true
    nvs:
      key: OTA_FILE
    ble:
      uuid: "{0x32,0x94,0x27,0x51,0x16,0x02,0x33,0x8b,0xa5,0xff,0x83,0xfd,0x9f,0xfd,0x10,0x3f}"
      write: true
    http:
      write: true
    default_var: CONFIG_OTA_FILENAME

  - name: i2c_sda
    caps_name: I2C_SDA
    integer: true
    nvs:
      key: I2C_SDA
    http:
      write: true
    default_var: DEFAULT_I2C_SDA

  - name: i2c_scl
    caps_name: I2C_SCL
    integer: true
    nvs:
      key: I2C_SCL
    http:
      write: true
    default_var: DEFAULT_I2C_SCL

  #
  # Custom keys
  #
  - name: state
    caps_name: STATE
    integer: true
    nvs:
      key: STATE
    ble:
      uuid: "{0x94,0x28,0x12,0x63,0x56,0xde,0xec,0x43,0xb4,0xfe,0xd6,0x3b,0xd2,0xdf,0xf6,0x8f}"
      write: true
      notify: true
    http:
      write: true
    default: FIRST_RUN

  - name: device_name
    caps_name: DEVICE_NAME
    string: true
    nvs:
      key: DEV_NAME
    ble:
      uuid: "{0x25,0x8b,0x4f,0x3d,0xf1,0x61,0xee,0x68,0x6e,0xee,0x0e,0x8c,0x32,0x77,0x31,0xa6}"
      write: true
    http:
      write: true
    default: SuperGreenDriver

  - name: timer_type
    caps_name: TIMER_TYPE
    integer: true
    nvs:
      key: TIMER_T
      manual: true
    ble:
      uuid: "{0xf3,0xa9,0xfa,0xb2,0x5a,0x41,0x3d,0x34,0x7b,0x0a,0xa9,0x3a,0x40,0xa8,0x5e,0x5f}"
      write: true
    http:
      write: true
    write_cb: true
    default_var: TIMER_MANUAL

  - name: timer_output
    caps_name: TIMER_OUTPUT
    integer: true
    nvs:
      key: TIMER_O
    http:
      noop: true
    default: 0

  - name: started_at
    caps_name: STARTED_AT
    integer: true
    nvs:
      key: ST_AT
    ble:
      uuid: "{0xa2,0x95,0x3b,0x05,0x4b,0x30,0x39,0xba,0x57,0x4f,0x01,0xf1,0x34,0x02,0x45,0x1f}"
      notify: true
      write: true
    http:
      write: true
    default: 0

  - name: on_hour
    caps_name: ON_HOUR
    integer: true
    nvs:
      key: ON_H
    ble:
      uuid: "{0xa1,0x4b,0xed,0x50,0xf3,0x19,0x26,0xef,0xda,0x09,0xb7,0x4a,0xa6,0xf9,0x67,0xe8}"
      write: true
    http:
      write: true
    default: 1

  - name: on_min
    caps_name: ON_MIN
    integer: true
    nvs:
      key: ON_M
    ble:
      uuid: "{0x47,0x13,0x79,0xf1,0x67,0x71,0xf5,0x62,0x14,0xf7,0x3b,0xdd,0x0b,0xa5,0x28,0x75}"
      write: true
    http:
      write: true
    default: 0

  - name: off_hour
    caps_name: OFF_HOUR
    integer: true
    nvs:
      key: OFF_H
    ble:
      uuid: "{0xae,0xbe,0x35,0x4c,0x29,0x12,0x53,0x02,0x6b,0xab,0x7e,0x9d,0x8c,0xb8,0xaf,0x5d}"
      write: true
    http:
      write: true
    default: 19

  - name: off_min
    caps_name: OFF_MIN
    integer: true
    nvs:
      key: OFF_M
    ble:
      uuid: "{0xd4,0xd3,0xef,0x05,0x3f,0x4f,0x10,0x41,0x22,0x2d,0xab,0xd9,0xe1,0xa1,0x6a,0x08}"
      write: true
    http:
      write: true
    default: 0

  - name: stretch
    caps_name: STRETCH
    integer: true
    nvs:
      key: STRETCH
    ble:
      uuid: "{0xe5,0x5a,0x87,0x47,0xcc,0xb2,0xe1,0xa5,0x22,0x48,0xb0,0x95,0x6b,0x32,0x72,0x70}"
      notify: true
    http:
      write: true
    write_cb: true
    default: 0

  - name: led_dim
    caps_name: LED_DIM
    integer: true
    nvs:
      key: LED_DIM
    ble:
      uuid: "{0x61,0xdb,0xb0,0x55,0xde,0x0f,0xb7,0x46,0x29,0xba,0x77,0x76,0xf6,0x75,0x63,0xa6}"
      notify: true
    http:
      write: true
    write_cb: true
    default: 0

  - name: blower
    caps_name: BLOWER
    integer: true
    nvs:
      key: BLWR
    ble:
      uuid: "{0x7b,0x5e,0x0a,0xb7,0x2a,0x7f,0xfd,0x1b,0x7f,0xe3,0xdc,0xbe,0xa7,0xce,0xb7,0x03}"
      notify: true
    http:
      write: true
    write_cb: true
    default: 50

  - name: sht1x_temp_c
    caps_name: SHT1X_TEMP_C
    integer: true
    nvs:
      key: SHT1X_C
    ble:
      uuid: "{0x25,0x8e,0x2d,0xf9,0x77,0x3d,0x9f,0xee,0x37,0x61,0x00,0x3b,0x36,0x28,0xab,0xb5}"
      notify: true
    http:
      noop: true
    default: -1000000

  - name: sht1x_temp_f
    caps_name: SHT1X_TEMP_F
    integer: true
    nvs:
      key: SHT1X_F
    ble:
      uuid: "{0x7b,0xac,0x28,0xbb,0xf8,0xaa,0x7c,0xde,0x31,0xee,0xab,0xa2,0x9d,0xc4,0xdd,0xbe}"
      notify: true
    http:
      noop: true
    default: -1000000

  - name: sht1x_humi
    caps_name: SHT1X_HUMI
    integer: true
    nvs:
      key: SHT1X_HU
    ble:
      uuid: "{0x29,0xdb,0x5c,0x3f,0xdb,0x0c,0x91,0x88,0x5c,0x1e,0x93,0xf9,0x4c,0x16,0xa7,0xba}"
      notify: true
    http:
      noop: true
    default: -1000000

  - name: led_info
    caps_name: LED_INFO
    string: true
    ble:
      uuid: "{0x96,0xc5,0x14,0x21,0x97,0x6a,0x70,0x18,0x34,0x52,0xce,0x6d,0xfe,0x81,0xf7,0x6d}"
      notify: true
    http:
      noop: true
    default: 

  - name: led_0_duty
    caps_name: LED_0_DUTY
    integer: true
    nvs:
      key: L_0_D
    http:
      write: true
    write_cb: true
    default: 0

  - name: led_1_duty
    caps_name: LED_1_DUTY
    integer: true
    nvs:
      key: L_1_D
    http:
      write: true
    write_cb: true
    default: 0

  - name: led_2_duty
    caps_name: LED_2_DUTY
    integer: true
    nvs:
      key: L_2_D
    http:
      write: true
    write_cb: true
    default: 0

  - name: led_3_duty
    caps_name: LED_3_DUTY
    integer: true
    nvs:
      key: L_3_D
    http:
      write: true
    write_cb: true
    default: 0

  - name: led_4_duty
    caps_name: LED_4_DUTY
    integer: true
    nvs:
      key: L_4_D
    http:
      write: true
    write_cb: true
    default: 0

  - name: led_5_duty
    caps_name: LED_5_DUTY
    integer: true
    nvs:
      key: L_5_D
    http:
      write: true
    write_cb: true
    default: 0

  - name: led_0_gpio
    caps_name: LED_0_GPIO
    integer: true
    nvs:
      key: L_0_IO
    http:
      write: true
    default: 0

  - name: led_1_gpio
    caps_name: LED_1_GPIO
    integer: true
    nvs:
      key: L_1_IO
    http:
      write: true
    default: 0

  - name: led_2_gpio
    caps_name: LED_2_GPIO
    integer: true
    nvs:
      key: L_2_IO
    http:
      write: true
    default: 0

  - name: led_3_gpio
    caps_name: LED_3_GPIO
    integer: true
    nvs:
      key: L_3_IO
    http:
      write: true
    default: 0

  - name: led_4_gpio
    caps_name: LED_4_GPIO
    integer: true
    nvs:
      key: L_4_IO
    http:
      write: true
    default: 0

  - name: led_5_gpio
    caps_name: LED_5_GPIO
    integer: true
    nvs:
      key: L_5_IO
    http:
      write: true
    default: 0

  - name: led_0_x
    caps_name: LED_0_X
    integer: true
    nvs:
      key: L_0_X
    http:
      write: true
    default: 0

  - name: led_1_x
    caps_name: LED_1_X
    integer: true
    nvs:
      key: L_1_X
    http:
      write: true
    default: 0

  - name: led_2_x
    caps_name: LED_2_X
    integer: true
    nvs:
      key: L_2_X
    http:
      write: true
    default: 0

  - name: led_3_x
    caps_name: LED_3_X
    integer: true
    nvs:
      key: L_3_X
    http:
      write: true
    default: 0

  - name: led_4_x
    caps_name: LED_4_X
    integer: true
    nvs:
      key: L_4_X
    http:
      write: true
    default: 0

  - name: led_5_x
    caps_name: LED_5_X
    integer: true
    nvs:
      key: L_5_X
    http:
      write: true
    default: 0

  - name: led_0_y
    caps_name: LED_0_Y
    integer: true
    nvs:
      key: L_0_Y
    http:
      write: true
    default: 0

  - name: led_1_y
    caps_name: LED_1_Y
    integer: true
    nvs:
      key: L_1_Y
    http:
      write: true
    default: 0

  - name: led_2_y
    caps_name: LED_2_Y
    integer: true
    nvs:
      key: L_2_Y
    http:
      write: true
    default: 0

  - name: led_3_y
    caps_name: LED_3_Y
    integer: true
    nvs:
      key: L_3_Y
    http:
      write: true
    default: 0

  - name: led_4_y
    caps_name: LED_4_Y
    integer: true
    nvs:
      key: L_4_Y
    http:
      write: true
    default: 0

  - name: led_5_y
    caps_name: LED_5_Y
    integer: true
    nvs:
      key: L_5_Y
    http:
      write: true
    default: 0

  - name: led_0_z
    caps_name: LED_0_Z
    integer: true
    nvs:
      key: L_0_Z
    http:
      write: true
    default: 0

  - name: led_1_z
    caps_name: LED_1_Z
    integer: true
    nvs:
      key: L_1_Z
    http:
      write: true
    default: 0

  - name: led_2_z
    caps_name: LED_2_Z
    integer: true
    nvs:
      key: L_2_Z
    http:
      write: true
    default: 0

  - name: led_3_z
    caps_name: LED_3_Z
    integer: true
    nvs:
      key: L_3_Z
    http:
      write: true
    default: 0

  - name: led_4_z
    caps_name: LED_4_Z
    integer: true
    nvs:
      key: L_4_Z
    http:
      write: true
    default: 0

  - name: led_5_z
    caps_name: LED_5_Z
    integer: true
    nvs:
      key: L_5_Z
    http:
      write: true
    default: 0
